MAJORS_LIST : list = ['Literary Journalism', 'International Studies', 'Data Science', 'Sociology', 
                 'Chinese Studies', 'German Studies', 'Civil Engineering', 'Environmental Engineering', 
                 'Biological Sciences', 'Game Design and Interactive Media', 'Mechanical Engineering', 
                 'Exercise Sciences', 'Philosophy', 'Mathematics', 'Classics', 'Biomedical Engineering', 
                 'Business Economics', 'Quantitative Economics', 'Spanish', 'Japanese Language and Literature', 
                 'Applied and Computational Mathematics', 'Art', 'Global Middle East Studies', 'Public Health Policy', 
                 'Chemical Engineering', 'East Asian Cultures', 'Physics', 'Asian American Studies', 'Electrical Engineering', 
                 'Biomedical Engineering; Premedical', 'Anthropology', 'Nursing Science', 'Korean Literature and Culture', 'History', 
                 'Gender and Sexuality Studies', 'Ecology and Evolutionary Biology', 'Developmental and Cell Biology', 'Genetics', 
                 'Applied Physics', 'Public Health Sciences', 'Computer Engineering', 'Music', 'Biology/Education', 
                 'Software Engineering', 'Psychology', 'Global Cultures', 'Social Ecology', 'European Studies', 
                 'Biochemistry and Molecular Biology', 'Neurobiology', 'Dance', 'Information and Computer Science', 
                 'Criminology, Law and Society', 'Education Sciences', 'Business Administration', 'Materials Science and Engineering', 
                 'Business Information Management', 'Dance, ', 'Religious Studies', 'Drama', 'Language Science', 'Political Science', 
                 'Comparative Literature', 'Informatics', 'Computer Science', 'Pharmaceutical Sciences', 'Film and Media Studies', 
                 'Biomedical Engineering: Premedical', 'Psychological Science', 'Microbiology and Immunology', 'Chemistry', 
                 'African American Studies', 'Chicano/Latino Studies', 'French', 'Social Policy and Public Service', 
                 'Earth System Science', 'Art History', 'Cognitive Sciences', 'Urban Studies', 
                 'English', 'Aerospace Engineering', 'Economics']
MAJORS = {
    'aerospace engineering': 'https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofmechanicalandaerospaceengineering/aerospaceengineering_bs/',
    'african american studies': 'https://catalogue.uci.edu/schoolofhumanities/departmentofafricanamericanstudies/africanamericanstudies_ba/',
    'anthropology': 'https://catalogue.uci.edu/schoolofsocialsciences/departmentofanthropology/anthropology_ba/',
    'applied and computational mathematics': 'https://catalogue.uci.edu/schoolofphysicalsciences/departmentofmathematics/appliedandcomputationalmathematics_bs/',
    'applied physics': 'https://catalogue.uci.edu/schoolofphysicalsciences/departmentofphysicsandastronomy/appliedphysics_bs/',
    'art': 'https://catalogue.uci.edu/clairetrevorschoolofthearts/departmentofart/art_ba/',
    'art history': 'https://catalogue.uci.edu/schoolofhumanities/departmentofarthistory/arthistory_ba/',
    'asian american studies': 'https://catalogue.uci.edu/schoolofhumanities/departmentofasianamericanstudies/asianamericanstudies_ba/',
    'biochemistry and molecular biology': 'https://catalogue.uci.edu/charliedunlopschoolofbiologicalsciences/departmentofmolecularbiologyandbiochemistry/biochemistryandmolecularbiology_bs/',
    'biological sciences': 'https://catalogue.uci.edu/charliedunlopschoolofbiologicalsciences/biologicalsciences_bs/',
    'biology/education': 'https://catalogue.uci.edu/charliedunlopschoolofbiologicalsciences/biologyeducation_bs/',
    'biomedical engineering': 'https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofbiomedicalengineering/biomedicalengineering_bs/',
    'biomedical engineering: premedical': 'https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofbiomedicalengineering/biomedicalengineeringpremedical_bs/',
    'business administration': 'https://catalogue.uci.edu/thepaulmerageschoolofbusiness/businessadministration_ba/',
    'business economics': 'https://catalogue.uci.edu/schoolofsocialsciences/departmentofeconomics/businesseconomics_ba/',
    'chemical engineering': 'https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofchemicalandbiomolecularengineering/chemicalengineering_bs/',
    'chemistry': 'https://catalogue.uci.edu/schoolofphysicalsciences/departmentofchemistry/chemistry_bs/',
    'chicano/latino studies': 'https://catalogue.uci.edu/schoolofsocialsciences/departmentofchicanolatinostudies/chicanolatinostudies_ba/',
    'chinese studies': 'https://catalogue.uci.edu/schoolofhumanities/departmentofeastasianstudies/chinesestudies_ba/',
    'civil engineering': 'https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofcivilandenvironmentalengineering/civilengineering_bs/',
    'classics': 'https://catalogue.uci.edu/schoolofhumanities/departmentofclassics/classics_ba/',
    'cognitive sciences': 'https://catalogue.uci.edu/schoolofsocialsciences/departmentofcognitivesciences/cognitivesciences_bs/',
    'comparative literature': 'https://catalogue.uci.edu/schoolofhumanities/departmentofcomparativeliterature/comparativeliterature_ba/',
    'computer engineering': 'https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofelectricalengineeringandcomputerscience/computerengineering_bs/',
    'computer science': 'https://catalogue.uci.edu/donaldbrenschoolofinformationandcomputersciences/departmentofcomputerscience/computerscience_bs/',
    'criminology, law and society': 'https://catalogue.uci.edu/schoolofsocialecology/departmentofcriminologylawandsociety/criminologylawandsociety_ba/',
    'dance': 'https://catalogue.uci.edu/clairetrevorschoolofthearts/departmentofdance/dance_ba/',
    'dance, ': 'https://catalogue.uci.edu/clairetrevorschoolofthearts/departmentofdance/dance_bfa/',
    'data science': 'https://catalogue.uci.edu/donaldbrenschoolofinformationandcomputersciences/departmentofstatistics/datascience_bs/',
    'developmental and cell biology': 'https://catalogue.uci.edu/charliedunlopschoolofbiologicalsciences/departmentofdevelopmentalandcellbiology/developmentalandcellbiology_bs/',
    'drama': 'https://catalogue.uci.edu/clairetrevorschoolofthearts/departmentofdrama/drama_ba/',
    'earth system science': 'https://catalogue.uci.edu/schoolofphysicalsciences/departmentofearthsystemscience/earthsystemscience_bs/',
    'east asian cultures': 'https://catalogue.uci.edu/schoolofhumanities/departmentofeastasianstudies/eastasiancultures_ba/',
    'ecology and evolutionary biology': 'https://catalogue.uci.edu/charliedunlopschoolofbiologicalsciences/departmentofecologyandevolutionarybiology/ecologyandevolutionarybiology_bs/',
    'economics': 'https://catalogue.uci.edu/schoolofsocialsciences/departmentofeconomics/economics_ba/',
    'education sciences': 'https://catalogue.uci.edu/schoolofeducation/education_ba/',
    'electrical engineering': 'https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofelectricalengineeringandcomputerscience/electricalengineering_bs/',
    'english': 'https://catalogue.uci.edu/schoolofhumanities/departmentofenglish/english_ba/',
    'environmental engineering': 'https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofcivilandenvironmentalengineering/environmentalengineering_bs/',
    'european studies': 'https://catalogue.uci.edu/schoolofhumanities/departmentofeuropeanlanguagesandstudies/europeanstudies_ba/',
    'exercise sciences': 'https://catalogue.uci.edu/charliedunlopschoolofbiologicalsciences/exercisesciences_bs/',
    'film and media studies': 'https://catalogue.uci.edu/schoolofhumanities/departmentoffilmandmediastudies/filmandmediastudies_ba/',
    'french': 'https://catalogue.uci.edu/schoolofhumanities/departmentofeuropeanlanguagesandstudies/french_ba/',
    'game design and interactive media': 'https://catalogue.uci.edu/donaldbrenschoolofinformationandcomputersciences/departmentofinformatics/gamedesignandinteractivemedia_bs/',
    'gender and sexuality studies': 'https://catalogue.uci.edu/schoolofhumanities/departmentofgenderandsexualitystudies/genderandsexualitystudies_ba/',
    'genetics': 'https://catalogue.uci.edu/charliedunlopschoolofbiologicalsciences/departmentofdevelopmentalandcellbiology/genetics_bs/',
    'german studies': 'https://catalogue.uci.edu/schoolofhumanities/departmentofeuropeanlanguagesandstudies/germanstudies_ba/',
    'global cultures': 'https://catalogue.uci.edu/schoolofhumanities/undergraduateprograminglobalcultures/globalcultures_ba/',
    'global middle east studies': 'https://catalogue.uci.edu/interdisciplinarystudies/globalmiddleeaststudies_ba/',
    'history': 'https://catalogue.uci.edu/schoolofhumanities/departmentofhistory/history_ba/',
    'informatics': 'https://catalogue.uci.edu/donaldbrenschoolofinformationandcomputersciences/departmentofinformatics/informatics_bs/',
    'information and computer science': 'https://catalogue.uci.edu/donaldbrenschoolofinformationandcomputersciences/informationandcomputerscience_bs/',
    'international studies': 'https://catalogue.uci.edu/schoolofsocialsciences/departmentofglobalandinternationalstudies/internationalstudies_ba/',
    'japanese language and literature': 'https://catalogue.uci.edu/schoolofhumanities/departmentofeastasianstudies/japaneselanguageandliterature_ba/',
    'korean literature and culture': 'https://catalogue.uci.edu/schoolofhumanities/departmentofeastasianstudies/koreanliteratureandculture_ba/',
    'language science': 'https://catalogue.uci.edu/schoolofsocialsciences/departmentoflanguagescience/languagescience_ba/',
    'literary journalism': 'https://catalogue.uci.edu/schoolofhumanities/departmentofenglish/literaryjournalism_ba/',
    'materials science and engineering': 'https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofmaterialsscienceandengineering/materialsscienceandengineering_bs/',
    'mathematics': 'https://catalogue.uci.edu/schoolofphysicalsciences/departmentofmathematics/mathematics_bs/',
    'mechanical engineering': 'https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofmechanicalandaerospaceengineering/mechanicalengineering_bs/',
    'microbiology and immunology': 'https://catalogue.uci.edu/charliedunlopschoolofbiologicalsciences/departmentofmolecularbiologyandbiochemistry/microbiologyandimmunology_bs/',
    'music': 'https://catalogue.uci.edu/clairetrevorschoolofthearts/departmentofmusic/music_ba/',
    'neurobiology': 'https://catalogue.uci.edu/charliedunlopschoolofbiologicalsciences/departmentofneurobiologyandbehavior/neurobiology_bs/',
    'nursing science': 'https://catalogue.uci.edu/sueandbillgrossschoolofnursing/nursingscience_bs/',
    'pharmaceutical sciences': 'https://catalogue.uci.edu/schoolofpharmacyandpharmaceuticalsciences/pharmaceuticalsciences_bs/',
    'philosophy': 'https://catalogue.uci.edu/schoolofhumanities/departmentofphilosophy/philosophy_ba/',
    'physics': 'https://catalogue.uci.edu/schoolofphysicalsciences/departmentofphysicsandastronomy/physics_bs/',
    'political science': 'https://catalogue.uci.edu/schoolofsocialsciences/departmentofpoliticalscience/politicalscience_ba/',
    'psychology': 'https://catalogue.uci.edu/schoolofsocialsciences/departmentofcognitivesciences/psychology_ba/',
    'psychological science': 'https://catalogue.uci.edu/schoolofsocialecology/departmentofpsychologicalscience/psychologicalscience_ba/',
    'public health policy': 'https://catalogue.uci.edu/joecwenschoolofpopulationandpublichealth/publichealthpolicy_ba/',
    'public health sciences': 'https://catalogue.uci.edu/joecwenschoolofpopulationandpublichealth/publichealthsciences_bs/',
    'quantitative economics': 'https://catalogue.uci.edu/schoolofsocialsciences/departmentofeconomics/quantitativeeconomics_ba/',
    'religious studies': 'https://catalogue.uci.edu/schoolofhumanities/undergraduateprograminreligiousstudies/religiousstudies_ba/',
    'social ecology': 'https://catalogue.uci.edu/schoolofsocialecology/socialecology_ba/',
    'social policy and public service': 'https://catalogue.uci.edu/schoolofsocialsciences/socialpolicyandpublicservice_ba/',
    'sociology': 'https://catalogue.uci.edu/schoolofsocialsciences/departmentofsociology/sociology_ba/',
    'software engineering': 'https://catalogue.uci.edu/donaldbrenschoolofinformationandcomputersciences/softwareengineering_bs/',
    'spanish': 'https://catalogue.uci.edu/schoolofhumanities/departmentofspanishandportuguese/spanish_ba/',
    'urban studies': 'https://catalogue.uci.edu/schoolofsocialecology/departmentofurbanplanningandpublicpolicy/urbanstudies_ba/',
    'business information management': 'https://catalogue.uci.edu/interdisciplinarystudies/businessinformationmanagement_bs/',
}

# {
#     "Aerospace Engineering, B.S.": "https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofmechanicalandaerospaceengineering/aerospaceengineering_bs/",
#     "African American Studies, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofafricanamericanstudies/africanamericanstudies_ba/",
#     "Anthropology, B.A.": "https://catalogue.uci.edu/schoolofsocialsciences/departmentofanthropology/anthropology_ba/",
#     "Applied and Computational Mathematics, B.S.": "https://catalogue.uci.edu/schoolofphysicalsciences/departmentofmathematics/appliedandcomputationalmathematics_bs/",
#     "Applied Physics, B.S.": "https://catalogue.uci.edu/schoolofphysicalsciences/departmentofphysicsandastronomy/appliedphysics_bs/",
#     "Art History, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofarthistory/arthistory_ba/",
#     "Art, B.A.": "https://catalogue.uci.edu/clairetrevorschoolofthearts/departmentofart/art_ba/",
#     "Asian American Studies, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofasianamericanstudies/asianamericanstudies_ba/",
#     "Biochemistry and Molecular Biology, B.S.": "https://catalogue.uci.edu/schoolofbiologicalsciences/departmentofmolecularbiologyandbiochemistry/biochemistryandmolecularbiology_bs/",
#     "Biological Sciences, B.S.": "https://catalogue.uci.edu/schoolofbiologicalsciences/biologicalsciences_bs/",
#     "Biology/Education, B.S.": "https://catalogue.uci.edu/schoolofbiologicalsciences/biologyeducation_bs/",
#     "Biomedical Engineering, B.S.": "https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofbiomedicalengineering/biomedicalengineering_bs/",
#     "Biomedical Engineering: Premedical, B.S.": "https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofbiomedicalengineering/biomedicalengineeringpremedical_bs/",
#     "Business Administration, B.A.": "https://catalogue.uci.edu/thepaulmeragegraduateschoolofbusiness/businessadministration_ba/",
#     "Business Economics, B.A.": "https://catalogue.uci.edu/schoolofsocialsciences/departmentofeconomics/businesseconomics_ba/",
#     "Business Information Management, B.S.": "https://catalogue.uci.edu/donaldbrenschoolofinformationandcomputersciences/businessinformationmanagement_bs/",
#     "Chemical Engineering, B.S.": "https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofchemicalengineeringandmaterialsengineering/chemicalengineering_bs/",
#     "Chemistry, B.S.": "https://catalogue.uci.edu/schoolofphysicalsciences/departmentofchemistry/chemistry_bs/",
#     "Chicano/Latino Studies, B.A.": "https://catalogue.uci.edu/schoolofsocialsciences/departmentofchicanolatinostudies/chicanolatinostudies_ba/",
#     "Chinese Studies, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofeastasianstudies/chinesestudies_ba/",
#     "Civil Engineering, B.S.": "https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofcivilandenvironmentalengineering/civilengineering_bs/",
#     "Classics, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofclassics/classics_ba/",
#     "Cognitive Sciences, B.S.": "https://catalogue.uci.edu/schoolofsocialsciences/departmentofcognitivesciences/cognitivesciences_bs/",
#     "Comparative Literature, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofcomplit/comparativeliterature_ba/",
#     "Computer Engineering, B.S.": "https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofelectricalengineeringandcomputerscience/computerengineering_bs/",
#     "Computer Science, B.S.": "https://catalogue.uci.edu/donaldbrenschoolofinformationandcomputersciences/departmentofcomputerscience/computerscience_bs/",
#     "Criminology, Law and Society, B.A.": "https://catalogue.uci.edu/schoolofsocialecology/departmentofcriminologylawandsociety/criminologylawandsociety_ba/",
#     "Dance, B.A.": "https://catalogue.uci.edu/clairetrevorschoolofthearts/departmentofdance/dance_ba/",
#     "Data Science, B.S.": "https://catalogue.uci.edu/donaldbrenschoolofinformationandcomputersciences/datascience_bs/",
#     "Developmental and Cell Biology, B.S.": "https://catalogue.uci.edu/schoolofbiologicalsciences/departmentofdevelopmentalandcellbiology/developmentalandcellbiology_bs/",
#     "Drama, B.A.": "https://catalogue.uci.edu/clairetrevorschoolofthearts/departmentofdrama/drama_ba/",
#     "Earth System Science, B.S.": "https://catalogue.uci.edu/schoolofphysicalsciences/departmentofearthsystemscience/earthsystemscience_bs/",
#     "East Asian Cultures, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofeastasianstudies/eastasiancultures_ba/",
#     "Ecology and Evolutionary Biology, B.S.": "https://catalogue.uci.edu/schoolofbiologicalsciences/departmentofecologyandevolutionarybiology/ecologyandevolutionarybiology_bs/",
#     "Economics, B.A.": "https://catalogue.uci.edu/schoolofsocialsciences/departmentofeconomics/economics_ba/",
#     "Education Sciences, B.A.": "https://catalogue.uci.edu/schoolofeducation/educationsciences_ba/",
#     "Electrical Engineering, B.S.": "https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofelectricalengineeringandcomputerscience/electricalengineering_bs/",
#     "English, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofenglish/english_ba/",
#     "Environmental Engineering, B.S.": "https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofcivilandenvironmentalengineering/environmentalengineering_bs/",
#     "European Studies, B.A.": "https://catalogue.uci.edu/schoolofhumanities/europeanstudies_ba/",
#     "Exercise Sciences, B.S.": "https://catalogue.uci.edu/schoolofbiologicalsciences/exercisesciences_bs/",
#     "Film and Media Studies, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentoffilmandmediastudies/filmandmediastudies_ba/",
#     "French, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofeuropeanlanguagesandstudies/french_ba/",
#     "Game Design and Interactive Media, B.S.": "https://catalogue.uci.edu/clairetrevorschoolofthearts/gamedesignandinteractivemedia_bs/",
#     "Gender and Sexuality Studies, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofgenderandsexualitystudies/genderandsexualitystudies_ba/",
#     "Genetics, B.S.": "https://catalogue.uci.edu/schoolofbiologicalsciences/departmentofdevelopmentalandcellbiology/genetics_bs/",
#     "German Studies, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofeuropeanlanguagesandstudies/germanstudies_ba/",
#     "Global Cultures, B.A.": "https://catalogue.uci.edu/schoolofhumanities/globalcultures_ba/",
#     "Global Middle East Studies, B.A.": "https://catalogue.uci.edu/schoolofhumanities/globalmiddleeaststudies_ba/",
#     "History, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofhistory/history_ba/",
#     "Informatics, B.S.": "https://catalogue.uci.edu/donaldbrenschoolofinformationandcomputersciences/departmentofinformatics/informatics_bs/",
#     "Information and Computer Science, B.S.": "https://catalogue.uci.edu/donaldbrenschoolofinformationandcomputersciences/informationandcomputerscience_bs/",
#     "International Studies, B.A.": "https://catalogue.uci.edu/schoolofsocialsciences/internationalstudies_ba/",
#     "Japanese Language and Literature, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofeastasianstudies/japaneselanguageandliterature_ba/",
#     "Korean Literature and Culture, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofeastasianstudies/koreanliteratureandculture_ba/",
#     "Language Science, B.A.": "https://catalogue.uci.edu/schoolofsocialsciences/languagescience_ba/",
#     "Literary Journalism, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofenglish/literaryjournalism_ba/",
#     "Materials Science and Engineering, B.S.": "https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofchemicalengineeringandmaterialsengineering/materialsscienceandengineering_bs/",
#     "Mathematics, B.S.": "https://catalogue.uci.edu/schoolofphysicalsciences/departmentofmathematics/mathematics_bs/",
#     "Mechanical Engineering, B.S.": "https://catalogue.uci.edu/thehenrysamuelischoolofengineering/departmentofmechanicalandaerospaceengineering/mechanicalengineering_bs/",
#     "Microbiology and Immunology, B.S.": "https://catalogue.uci.edu/schoolofbiologicalsciences/departmentofmolecularbiologyandbiochemistry/microbiologyandimmunology_bs/",
#     "Music, B.A.": "https://catalogue.uci.edu/clairetrevorschoolofthearts/departmentofmusic/music_ba/",
#     "Neurobiology, B.S.": "https://catalogue.uci.edu/schoolofbiologicalsciences/departmentofneurobiologyandbehavior/neurobiology_bs/",
#     "Nursing Science, B.S.": "https://catalogue.uci.edu/sueandbillgrossschoolofnursing/nursingscience_bs/",
#     "Pharmaceutical Sciences, B.S.": "https://catalogue.uci.edu/schoolofpharmacyandpharmaceuticalsciences/pharmaceuticalsciences_bs/",
#     "Philosophy, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofphilosophy/philosophy_ba/",
#     "Physics, B.S.": "https://catalogue.uci.edu/schoolofphysicalsciences/departmentofphysicsandastronomy/physics_bs/",
#     "Political Science, B.A.": "https://catalogue.uci.edu/schoolofsocialsciences/departmentofpoliticalscience/politicalscience_ba/",
#     "Psychological Science, B.A.": "https://catalogue.uci.edu/schoolofsocialecology/departmentofpsychology/psychologicalscience_ba/",
#     "Psychology, B.S.": "https://catalogue.uci.edu/schoolofsocialsciences/departmentofcognitivesciences/psychology_bs/",
#     "Public Health Policy, B.A.": "https://catalogue.uci.edu/programinpublichealth/publichealthpolicy_ba/",
#     "Public Health Sciences, B.S.": "https://catalogue.uci.edu/programinpublichealth/publichealthsciences_bs/",
#     "Quantitative Economics, B.A.": "https://catalogue.uci.edu/schoolofsocialsciences/departmentofeconomics/quantitativeeconomics_ba/",
#     "Religious Studies, B.A.": "https://catalogue.uci.edu/schoolofhumanities/religiousstudies_ba/",
#     "Social Ecology, B.A.": "https://catalogue.uci.edu/schoolofsocialecology/socialecology_ba/",
#     "Social Policy and Public Service, B.A.": "https://catalogue.uci.edu/schoolofsocialecology/socialpolicyandpublicservice_ba/",
#     "Sociology, B.A.": "https://catalogue.uci.edu/schoolofsocialsciences/departmentofsociology/sociology_ba/",
#     "Software Engineering, B.S.": "https://catalogue.uci.edu/donaldbrenschoolofinformationandcomputersciences/departmentofinformatics/softwareengineering_bs/",
#     "Spanish, B.A.": "https://catalogue.uci.edu/schoolofhumanities/departmentofeuropeanlanguagesandstudies/spanish_ba/",
#     "Urban Studies, B.A.": "https://catalogue.uci.edu/schoolofsocialecology/departmentofurbanplanningandpublicpolicy/urbanstudies_ba/"
# }